import Head from 'next/head'
import React from 'react'
import Navbar from './Navbar'
import Footer from './Footer'

const Layout = ({ title, children }) => {
  return (
    <>
        <Head>
            <title>{title ? title + " | Terapia RA" : "Terapia RA"}</title>
            <link rel="icon" href="/favicon.ico" />
            <meta name="Terapia con Realidad Aumentada" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0"
            />
        </Head>
        <Navbar/>
          <main className="snap-y snap-mandatory relative w-full h-screen overflow-y-auto overflow-x-hidden scroll-smooth">
            {children}
          </main>
        {/* <Footer/> */}
    </>
  )
}

export default Layout