import Head from 'next/head'
import React, { useEffect } from 'react'
import Navbar from './Navbar'
import Footer from './Footer'

const Layout = ({ title, children }) => {

  useEffect(() =>{
    
    const headerEl = document.querySelector("#landing-header");
    const listItem = document.querySelectorAll("#landing-header li")
    const menuBackDrop = document.querySelector("#menu-backdrop");

    listItem.forEach((item) => {
      item.addEventListener("mouseenter", () => {
        const { left, top, width, height } = item.getBoundingClientRect()

        menuBackDrop.style.setProperty("--left", `${left}px`)
        menuBackDrop.style.setProperty("--top", `${top}px`)
        menuBackDrop.style.setProperty("--width", `${width}px`)
        menuBackDrop.style.setProperty("--height", `${height}px`)

        menuBackDrop.style.opacity = "1"
        menuBackDrop.style.visibility = "visible"
      })

      item.addEventListener("mouseleave", () => {
        menuBackDrop.style.opacity = "0"
        menuBackDrop.style.visibility = "hidden"
      })
    })

    const observerOptions = {
      root: null,
      rootMargin: "0px", // en cuanto se vea el elemento
      threshold: 0.9, // porcentaje de visibilidad
    }

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        const { isIntersecting } = entry
        if (isIntersecting) {
          const color = entry.target.getAttribute("data-header-color")
          headerEl.style.color = color
        }
      })
    }, observerOptions)

    const sectionElements = document.querySelectorAll(".landing-section")
    sectionElements.forEach((section) => observer.observe(section))
  }, [])


  return (
    <>
        <Head>
          <title>{title ? title + " | Terapia RA" : "Terapia RA"}</title>
          <link rel="icon" href="/favicon.ico" />
          <meta name="Terapia con Realidad Aumentada" content="Generated by create next app" />
          <meta
              name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0"
          />
        </Head>
        <Navbar/>
          <main className="snap-y snap-mandatory relative w-full h-screen overflow-y-auto overflow-x-hidden scroll-smooth">
            {children}
          </main>
        {/* <Footer/> */}
    </>
  )
}

export default Layout